language: node_js
node_js:
  - "6"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: B1HgMHQOSTNDuaGzuOMLS/guY5BPJEjxPHzcN5DuI4TxR46otvXP6PRdbqJGE3/8F9AVdmsYbwU8HNdKrMC/SUIsgJdzBkhQC5fZIUSakYcZ0QkloMwFAmI7HwwfRFfD1DuHW7COqSTme9pbUba2G5a3WQrfNugt9xI1FyoQoOpdcC97gAzpjXnOmp7DWtkkgyfWsOtxfW38vMulti0IlSRzZ1sXXwbvW5e+UuoMTZCZj1Bq8i+9jwhrNdEwbPuyZ5C9/wgvNKWu/Kl6u93nSr04N8njpc/GCGBJsUYkj68sTy2DG8VgUqhCyyO7skmSbL6d1asJl5N+3Zvs3IZWuQW/1R6ixJYkRycOmQLwVZpicpXWIyny1qh928Wyij9Q8ViX32qxGvcSdimZLeChuhMyyTGfcC35R4KwqvXcGZjCRDfMgjwz/uUeTHM3OynobX2rC5cfnjVgYUUUKhggQIcLkQFVpqMd7ByLJIyt4QLQUYCA4Iyy5IpHEj+qLcEbtoFfk443rdv4TI3po41yVsHr6KERThrFv7F0iu96JPr6BIvOPldmiDmVb4i4My8m5LdS4yb7Mv8raDaH6dHIHY1JD/IVk6mzmy9DVaFrVogXI58ABnVmIQBDQmhx9rXBuz8RI/iOkcqeazB1CMVdjxhALBaJLiZMh6VE4Vh8WG8=
  app: react-template-app
  on:
    repo: ramonrf/react-template
    branch: feature/add-heroku-deployment
